### ISSUE TITLE
Project has no LICENSE

### ISSUE THREAD

**Issue by aschrijver** [swentel/activitypub#26]
I am creating a new _developer resources_ page for the [Feneas wiki research area](https://git.feneas.org/feneas/fediverse/-/wikis/Home) and noticed that your project has no LICENSE, which technically makes it proprietary and not open-source.

On the [ActivityPub watchlist](https://git.feneas.org/feneas/fediverse/-/wikis/watchlist-for-activitypub-apps) you are referred to as having `CC0` public domain license, but I will have to correct that, unless there is clarity on the actual license you adhere to.

**Comment by swentel** [comment]
Hey,

The license will be GPL2 - mainly because the module will be distributed via drupal.org as well and that's the automatic license which is added by the package script over there.

I'll commit it to the repository somewhere this week! And will actually start working on it too next week :)

**Comment by swentel** [comment]
Done :)

**Comment by aschrijver** [comment]
Thank you! I have updated the page. You are first under Plugins (I named the project 'Drupal integration').

- [Watchlist for ActivityPub developer resources](https://git.feneas.org/feneas/fediverse/-/wikis/Watchlist-for-ActivityPub-developer-resources)
